# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.1,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.1.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Build and test
        run: |
          xcrun simctl list
          xcodebuild clean build -project QNota.xcodeproj -scheme QNota \
          -destination "${destination}" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
